CREATE TABLE IF NOT EXISTS `player_latest_points` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `player_id` INT NOT NULL REFERENCES `players`(`id`) ON DELETE CASCADE,
    `points` INT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (`player_id`)
)